### ISSUE TITLE
Samtools issue with larger assemblies

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#18]
Related to https://github.com/samtools/samtools/issues/74

The mapping never fully finishes

**Comment by necrolyte2** [comment]
Manual upgraded `samtools==1.2` on AFRIMS workstation yielded only 2 mutation count differences instead of the many ones that showed on travis build?
ONly thing I can think of is that travis looked at 780 first and then exited while the afrims computer looked at 947 first.
```
[root ngs_mapper]# conda search samtools
Fetching package metadata: ............
bioconductor-rsamtools       1.22.0                 r3.2.2_0  bioconda        
                             1.22.0                 r3.2.2_1  bioconda        
perl-bio-samtools            1.43                 pl5.22.0_0  BioBuilds       
samtools                     0.1.16                        0  bioconda        
                             0.1.17                        0  BioBuilds       
                             0.1.18                        0  bioconda        
                          .  0.1.19                        0  BioBuilds       
                             1.0                           0  bioconda        
                             1.1                           0  bioconda        
                             1.2                           0  bioconda        
                             1.2.0                         0  BioBuilds       
                             1.2.0                         1  BioBuilds       
                             1.2                           1  bioconda        
                          *  1.2                           2  bioconda        
                             1.3                           0  bioconda        
                             1.3.0            py27pl5.22.0_0  BioBuilds       
                          .  1.3                           1  bioconda        
[root ngs_mapper]# pushd /tmp/ngs_mappertests0j3llXpackage
/tmp/ngs_mappertests0j3llXpackage /opt/ngs_mapper
[root ngs_mappertests0j3llXpackage]# ls
graphsample.log  MapUnmapReads.png  pipeline.log  PipelineTimes.png  Projects  QualDepth.pdf  SampleCoverage.png  ss.tsv  vcf_consensus
[root ngs_mappertests0j3llXpackage]# cd Projects/
[root Projects]# ls
780  947
[root Projects]# cd 780
[root 780]# cd ../947/
[root 947]# ls
947.bam                  947.bam.qualdepth.json  947.log        947.ref.fasta.amb  947.ref.fasta.pac  947UiMIuWrunsample  flagstats.txt  trim_stats
947.bam.bai              947.bam.qualdepth.png   947.reads.png  947.ref.fasta.ann  947.ref.fasta.sa   bwa.log             qualdepth
947.bam.consensus.fasta  947.bam.vcf             947.ref.fasta  947.ref.fasta.bwt  947.std.log        filtered            trimmed_reads
[root@AF-VROD004993 947]# ig
igawk  igv    
[root 947]# vi 947.bam.consensus.fasta 
[root 947]# grep --color -i r 947.bam.consensus.fasta 
[root 947]# grep --color -i y 947.bam.consensus.fasta 
>947 Den4/AY618992_1/Thailand/2001/Den4_1
TTGAGGTGGAAGACTATGGATTTGGCATGTTCACGACCAACATATGGATGAAATTYCGAG
AAAGGAGGCTGCGAACCTTGATTCTGGCTCCYACGAGAGTGGTGGCGGCCGAAATGGAAG
TAATTGAAAAAACAAAAACGGATYTTGGGTTTTACCAGGTAAAAGCAGAAACCACCATCC
[root 947]# vi 947.bam.vcf 
[root 947]# ls
947.bam                  947.bam.qualdepth.json  947.log        947.ref.fasta.amb  947.ref.fasta.pac  947UiMIuWrunsample  flagstats.txt  trim_stats
947.bam.bai              947.bam.qualdepth.png   947.reads.png  947.ref.fasta.ann  947.ref.fasta.sa   bwa.log             qualdepth
947.bam.consensus.fasta  947.bam.vcf             947.ref.fasta  947.ref.fasta.bwt  947.std.log        filtered            trimmed_reads
[root 947]# grep -i --color n 947.bam.consensus.fasta 
>947 Den4/AY618992_1/Thailand/2001/Den4_1
[root 947]# which samtools
/opt/ngs_mapper/miniconda/bin/samtools
[root 947]# cd ..
[root Projects]# popd
/opt/ngs_mapper
[root ngs_mapper]# rm -rf /tmp/
3d4b4cf3-cd8f-4045-b26f-ff6ce5925b17  hsperfdata_training/                  pulse-bQtN7flEPSmC/                   virtual-root.c1oXDf/
Angkana/                              .ICE-unix/                            pulse-flc4TwPAL5sj/                   virtual-root.E4R7GJ/
ed6ed760-d3d9-4a4e-86fc-b703ceb3e7f9  keyring-XOONDf/                       pulse-GDyYkmtwPhgE/                   virtual-root.jN3xyK/
.esd-0/                               ngs_mappertests0j3llXpackage/         test_run.txt                          virtual-root.mWwnZV/
.esd-500/                             ngs_mappertestsfOLeufpackage/         thingy2                               virtual-root.N8vuLk/
.esd-501/                             ngs_mappertestsT9xfBtpackage/         tmp-prefs3437809343691504896.tmp      virtual-root.nHq0ZQ/
.esd-502/                             orbit-gdm/                            tmp-prefs586136902725630204.tmp       virtual-root.Nq5yAS/
FLEXnet/                              orbit-root/                           virtual-Angkana.awYq9m/               virtual-training.Nq8o3M/
gedit.training.3925972708             orbit-training/                       virtual-Angkana.QRwyIc/               virtual-training.TdAzG9/
gnome-system-monitor.root.3676391235  pulse-3DSkCmWiUgtn/                   virtual-root.5xAsoh/                  .X0-lock
hsperfdata_root/                      pulse-A8gCYCt4M1oN/                   virtual-root.B5fo4f/                  .X11-unix/
[root ngs_mapper]# rm -rf /tmp/ngs_mappertests*
[root ngs_mapper]# ngs_mapper/tests/slow_tests.sh 
ngs_mapper.tests.test_functional.TestRunPipeline.test_consensus_mutations ... FAIL
ngs_mapper.tests.test_functional.TestRunPipeline.test_pipeline_produced_expected_files_dirs ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_project_directories_have_expected_files ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_return_code_and_output ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_vcf_consensus_has_symlink_consensuses ... ok

======================================================================
FAIL: ngs_mapper.tests.test_functional.TestRunPipeline.test_consensus_mutations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/ngs_mapper/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/ngs_mapper/ngs_mapper/tests/test_functional.py", line 199, in test_consensus_mutations
    eq_([], diffs)
AssertionError: [] != ['Base r count for 947 Den4/AY618992_1/Thailand/2001/Den4_1: Expected 1: Result 0', 'Base y count for 947 Den4/AY618992_1/Thailand/2001/Den4_1: Expected 4: Result 3']
-------------------- >> begin captured stdout << ---------------------
runsamplesheet.sh /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional /tmp/ngs_mappertestsPfkGZEpackage/ss.tsv
--- Standard output ---
Using 24 cpus
2016-03-23 14:24:59,934 -- INFO -- runsample       --- Starting 947 --- 
2016-03-23 14:24:59,934 -- INFO -- runsample       --- Starting 780 --- 
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.fastq
5004 reads converted
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.fastq
/opt/ngs_mapper/miniconda/lib/python2.7/site-packages/Bio/SeqIO/SffIO.py:991: BiopythonParserWarning: Your SFF file is technically invalid as it is missing a terminal 4 byte null padding region.
  BiopythonParserWarning)
4821 reads converted

2016-03-23 14:25:43,080 -- INFO -- runsample       --- Finished 780 ---

2016-03-23 14:31:14,785 -- INFO -- runsample       --- Finished 947 ---
Using 24 cpus
2016-03-23 14:31:16,673 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png

real	0m2.016s
user	0m1.979s
sys	0m0.091s
2016-03-23 14:31:23,596 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

real	0m9.486s
user	0m13.422s
sys	0m0.185s
Reflen: 1732
Curregion: [1674, 1732, 'LowCoverage']
Reflen: 2193
Curregion: [1371, 2193, 'Normal']
Reflen: 1000
Curregion: [1, 1000, 'Normal']
Reflen: 1538
Curregion: [1517, 1524, 'LowCoverage']
Creating new gap region to cover end of reference: [1524, 1538, 'Gap']
Reflen: 2311
Curregion: [1801, 2311, 'Normal']
Reflen: 1438
Curregion: [934, 1438, 'LowCoverage']
Reflen: 10650
Curregion: [1, 10650, 'Normal']
Reflen: 861
Curregion: [1, 861, 'Normal']
Reflen: 2318
Curregion: [1617, 2318, 'Normal']
convert: DelegateLibrarySupportNotBuiltIn `QualDepth.pdf' (JPEG) @ error/pdf.c/WritePDFImage/1470.
2016-03-23 14:31:29,393 -- WARNING -- graph_times     Projects/780 ran in only 43 seconds
2016-03-23 14:31:29,393 -- INFO -- graph_times     Plotting all projects inside of Projects

--- End standard output ---
--- Graphsample log ---
2016-03-23 14:25:38,997 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/780sspdUVrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780sspdUVrunsample/780.bam.qualdepth.png
2016-03-23 14:30:56,297 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/947jC9z49runsample/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947jC9z49runsample/947.bam.qualdepth.png
2016-03-23 14:31:16,673 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png
2016-03-23 14:31:23,596 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

--- End Graphsample log ---
Base r count for 947 Den4/AY618992_1/Thailand/2001/Den4_1: Expected 1: Result 0
Base y count for 947 Den4/AY618992_1/Thailand/2001/Den4_1: Expected 4: Result 3

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 5 tests in 390.350s
```

**Comment by necrolyte2** [comment]
I added samtools to vdbwrair/conda-recipes so it is the same version that we used to use
```
[root ngs_mapper]# conda install samtools==0.1.19
Fetching package metadata: ............
Solving package specifications: .........

Package plan for installation in environment /opt/ngs_mapper/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ncurses-5.9                |                7         695 KB

The following NEW packages will be INSTALLED:

    ncurses:  5.9-7   

The following packages will be DOWNGRADED:

    samtools: 1.2-2 --> 0.1.19-0

Fetching packages ...
ncurses-5.9-7. 100% |#############################################################################################################################| Time: 0:00:03 214.70 kB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|################################################################################################################################################| 100%
[root ngs_mapper]# samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         tview       text alignment viewer
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         bedcov      read depth per BED region
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes
         bamshuf     shuffle and group alignments by name

[root ngs_mapper]# ngs_mapper/tests/
fast_tests.sh  fixtures/      slow_tests.sh  unit/          
[root@AF-VROD004993 ngs_mapper]# ngs_mapper/tests/slow_tests.sh 
ngs_mapper.tests.test_functional.TestRunPipeline.test_consensus_mutations ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_pipeline_produced_expected_files_dirs ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_project_directories_have_expected_files ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_return_code_and_output ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_vcf_consensus_has_symlink_consensuses ... ok

----------------------------------------------------------------------
Ran 5 tests in 379.402s

OK
```
