### ISSUE TITLE
NGS_MAPPER error

### ISSUE THREAD

**Issue by InaMBerry** [VDBWRAIR/ngs_mapper#189]
Getting following when running a new config.yaml file:
2016-03-08 13:42:54,552 -- INFO -- runsample       --- Starting 11108 --- 
2016-03-08 13:42:54,552 -- INFO -- runsample       --- Using custom config from newconfig.yaml ---
2016-03-08 13:45:10,402 -- INFO -- runsample       --- Finished 11100 ---
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.RuntimeError'> ignored

[samplesheet2.txt](https://github.com/VDBWRAIR/ngs_mapper/files/163771/samplesheet2.txt)
[Den2__Thailand_FJ906957__1996.fasta.txt](https://github.com/VDBWRAIR/ngs_mapper/files/163772/Den2__Thailand_FJ906957__1996.fasta.txt)
[Den2__Thailand_FJ810410__2001.fasta.txt](https://github.com/VDBWRAIR/ngs_mapper/files/163774/Den2__Thailand_FJ810410__2001.fasta.txt)
[newconfig.yaml.txt](https://github.com/VDBWRAIR/ngs_mapper/files/163775/newconfig.yaml.txt)

**Comment by necrolyte2** [comment]
Looks related to #130 

Seems it does not cause an issue with the results, but we need to verify that is the case

**Comment by averagehat** [comment]
@InaMBerry This is fixed locally. This issue is with an old version. I updated the module to 1.3.0 so it should now work.

**Comment by InaMBerry** [comment]
The new module is not working (so I am still using the old one). This is the error I get on the newest version:
2016-03-09 10:35:34,694 -- INFO -- runsample       --- Starting 11130 --- 
2016-03-09 10:35:35,793 -- ERROR -- runsample       
filtering with specifications, drop Ns:False, Index Quality Min:0
from folder /media/VD_Research/NGSData/ReadsBySample/11130 to folder Projects/11130/11130MScA43runsample/filtered
Traceback (most recent call last):
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/bin/ngs_filter", line 9, in <module>
    load_entry_point('ngs-mapper==1.2.4', 'console_scripts', 'ngs_filter')()
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/nfilter.py", line 145, in main
    outpaths = write_post_filter(args['<readdir>'], idxMin, dropNs, args['--outdir'], args['--parallel'])
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/nfilter.py", line 109, in write_post_filter
    return map_to_dir(readsdir, write_filters, parallel)
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/nfilter.py", line 67, in map_to_dir
    return map(func, files)
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/nfilter.py", line 96, in write_filtered
    outpath = name_filtered(readpath, outdir) 
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/nfilter.py", line 36, in name_filtered
    if not renamed.ends_with('.fastq'):
AttributeError: 'str' object has no attribute 'ends_with'

Traceback (most recent call last):
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/bin/graphsample", line 9, in <module>
    load_entry_point('ngs-mapper==1.2.4', 'console_scripts', 'graphsample')()
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graphsample.py", line 23, in main
    pngfile = make_image( jfile, args.outpath )
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graphsample.py", line 41, in make_image
    j = json.load( open(jfile) )
IOError: [Errno 2] No such file or directory: 'Projects/11130/11130.bam.qualdepth.json'
0.23user 0.11system 0:03.83elapsed 8%CPU (0avgtext+0avgdata 26920maxresident)k
32984inputs+16outputs (14major+8835minor)pagefaults 0swaps
Traceback (most recent call last):
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/bin/graph_mapunmap", line 9, in <module>
    load_entry_point('ngs-mapper==1.2.4', 'console_scripts', 'graph_mapunmap')()
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_mapunmap.py", line 140, in main
    make_graphic( args.jsons, args.outfile )
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_mapunmap.py", line 125, in make_graphic
    smu = get_mapunmap( jsons )
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_mapunmap.py", line 60, in get_mapunmap
    samples.append( sample_from_filename( jfile ) )
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_mapunmap.py", line 45, in sample_from_filename
    raise ValueError( "Filename given({0}) does not contain .bam".format(filename) )
ValueError: Filename given(Projects/*/*.qualdepth.json) does not contain .bam
Traceback (most recent call last):
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/bin/sample_coverage", line 9, in <module>
    load_entry_point('ngs-mapper==1.2.4', 'console_scripts', 'sample_coverage')()
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/coverage.py", line 412, in main
    fig = create_figure_for_projects(projects, includes, excludes, lineargs, regionmins)
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/coverage.py", line 315, in create_figure_for_projects
    allrefs = get_allrefs(projects, includes, excludes)
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/coverage.py", line 140, in get_allrefs
    allrefs.update(refs_from_project(p, includes, excludes))
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/coverage.py", line 125, in refs_from_project
    qualdepths = load_project_qualdepth(projectpath)
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/coverage.py", line 150, in load_project_qualdepth
    raise ValueError('{0} missing qualdepth file'.format(projpath))
ValueError: Projects/11130 missing qualdepth file
convert: unable to open image `Projects/*/*.qualdepth.png': No such file or directory @ error/blob.c/OpenBlob/2588.
convert: unable to open file `Projects/*/*.qualdepth.png' @ error/png.c/ReadPNGImage/3639.
convert: missing an image filename `QualDepth.pdf' @ error/convert.c/ConvertImageCommand/3015.
Traceback (most recent call last):
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/bin/graph_times", line 9, in <module>
    load_entry_point('ngs-mapper==1.2.4', 'console_scripts', 'graph_times')()
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_times.py", line 15, in main
    ss = start_stop( 'Projects' )
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_times.py", line 57, in start_stop
    diff = datediff( start_stop_for_project( p ) )
  File "/media/VD_Research/Admin/PBS/Software/ngs_mapper-1.3.0/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.2.4-py2.7.egg/ngs_mapper/graph_times.py", line 73, in start_stop_for_project
    with open( log ) as fh:
IOError: [Errno 2] No such file or directory: 'Projects/11130/11130.log'
ln: target `vcf_consensus/*.consensus.fasta.fasta' is not a directory

**Comment by necrolyte2** [comment]
We will get the bug fixed(#190) for the new version soon

For the version you are using just ignore the errors as they do not seem to affect the output

**Comment by averagehat** [comment]
@InaMBerry This should be fixed locally next time you run ngs_mapper.

**Comment by averagehat** [comment]
Closing this as the problem was with an old version.
