### ISSUE TITLE
Error when running slow_tests.sh

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#209]
```
# ngs_mapper/tests/slow_tests.sh 
ngs_mapper.tests.test_functional.TestRunPipeline.test_consensus_mutations ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_pipeline_produced_expected_files_dirs ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_project_directories_have_expected_files ... FAIL
ngs_mapper.tests.test_functional.TestRunPipeline.test_return_code_and_output ... ok
ngs_mapper.tests.test_functional.TestRunPipeline.test_vcf_consensus_has_symlink_consensuses ... ok

======================================================================
FAIL: ngs_mapper.tests.test_functional.TestRunPipeline.test_project_directories_have_expected_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/ngs_mapper/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/ngs_mapper/ngs_mapper/tests/test_functional.py", line 141, in test_project_directories_have_expected_files
    self.check_sample_project_files( projdir, fixture )
  File "/opt/ngs_mapper/ngs_mapper/tests/test_functional.py", line 115, in check_sample_project_files
    ok_( False )
AssertionError: None
-------------------- >> begin captured stdout << ---------------------
runsamplesheet.sh /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional /tmp/ngs_mappertestsU890q7package/ss.tsv
--- Standard output ---
Using 24 cpus
2016-03-23 16:31:11,420 -- INFO -- runsample       --- Starting 947 --- 
2016-03-23 16:31:11,420 -- INFO -- runsample       --- Starting 780 --- 
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.fastq
5004 reads converted
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.fastq
/opt/ngs_mapper/miniconda/lib/python2.7/site-packages/Bio/SeqIO/SffIO.py:991: BiopythonParserWarning: Your SFF file is technically invalid as it is missing a terminal 4 byte null padding region.
  BiopythonParserWarning)
4821 reads converted

2016-03-23 16:31:53,707 -- INFO -- runsample       --- Finished 780 ---

2016-03-23 16:37:16,392 -- INFO -- runsample       --- Finished 947 ---
Using 24 cpus
Qt: Session management error: None of the authentication protocols specified are supported
Qt: Session management error: None of the authentication protocols specified are supported
2016-03-23 16:37:18,365 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png

real	0m2.107s
user	0m2.045s
sys	0m0.110s
2016-03-23 16:37:24,990 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

real	0m9.281s
user	0m13.305s
sys	0m0.169s
Qt: Session management error: None of the authentication protocols specified are supported
Qt: Session management error: None of the authentication protocols specified are supported
Reflen: 1732
Curregion: [1713, 1732, 'LowCoverage']
Reflen: 2193
Curregion: [1371, 2193, 'Normal']
Reflen: 1000
Curregion: [1, 1000, 'Normal']
Reflen: 1538
Curregion: [1517, 1524, 'LowCoverage']
Creating new gap region to cover end of reference: [1524, 1538, 'Gap']
Reflen: 2311
Curregion: [1801, 2311, 'Normal']
Reflen: 1438
Curregion: [1335, 1438, 'LowCoverage']
Reflen: 10650
Curregion: [1, 10650, 'Normal']
Reflen: 861
Curregion: [1, 861, 'Normal']
Reflen: 2318
Curregion: [1617, 2318, 'Normal']
convert: DelegateLibrarySupportNotBuiltIn `QualDepth.pdf' (JPEG) @ error/pdf.c/WritePDFImage/1470.
2016-03-23 16:37:30,863 -- WARNING -- graph_times     Projects/780 ran in only 42 seconds
2016-03-23 16:37:30,863 -- INFO -- graph_times     Plotting all projects inside of Projects
Qt: Session management error: None of the authentication protocols specified are supported

--- End standard output ---
--- Graphsample log ---
2016-03-23 16:31:49,572 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/7806rzqSDrunsample/780.bam.qualdepth.png
2016-03-23 16:36:57,424 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/947PQ58Shrunsample/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947PQ58Shrunsample/947.bam.qualdepth.png
2016-03-23 16:37:18,365 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png
2016-03-23 16:37:24,990 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

--- End Graphsample log ---
--- Standard output ---
Using 24 cpus
2016-03-23 16:31:11,420 -- INFO -- runsample       --- Starting 947 --- 
2016-03-23 16:31:11,420 -- INFO -- runsample       --- Starting 780 --- 
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.fastq
5004 reads converted
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.fastq
/opt/ngs_mapper/miniconda/lib/python2.7/site-packages/Bio/SeqIO/SffIO.py:991: BiopythonParserWarning: Your SFF file is technically invalid as it is missing a terminal 4 byte null padding region.
  BiopythonParserWarning)
4821 reads converted

2016-03-23 16:31:53,707 -- INFO -- runsample       --- Finished 780 ---

2016-03-23 16:37:16,392 -- INFO -- runsample       --- Finished 947 ---
Using 24 cpus
Qt: Session management error: None of the authentication protocols specified are supported
Qt: Session management error: None of the authentication protocols specified are supported
2016-03-23 16:37:18,365 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png

real	0m2.107s
user	0m2.045s
sys	0m0.110s
2016-03-23 16:37:24,990 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

real	0m9.281s
user	0m13.305s
sys	0m0.169s
Qt: Session management error: None of the authentication protocols specified are supported
Qt: Session management error: None of the authentication protocols specified are supported
Reflen: 1732
Curregion: [1713, 1732, 'LowCoverage']
Reflen: 2193
Curregion: [1371, 2193, 'Normal']
Reflen: 1000
Curregion: [1, 1000, 'Normal']
Reflen: 1538
Curregion: [1517, 1524, 'LowCoverage']
Creating new gap region to cover end of reference: [1524, 1538, 'Gap']
Reflen: 2311
Curregion: [1801, 2311, 'Normal']
Reflen: 1438
Curregion: [1335, 1438, 'LowCoverage']
Reflen: 10650
Curregion: [1, 10650, 'Normal']
Reflen: 861
Curregion: [1, 861, 'Normal']
Reflen: 2318
Curregion: [1617, 2318, 'Normal']
convert: DelegateLibrarySupportNotBuiltIn `QualDepth.pdf' (JPEG) @ error/pdf.c/WritePDFImage/1470.
2016-03-23 16:37:30,863 -- WARNING -- graph_times     Projects/780 ran in only 42 seconds
2016-03-23 16:37:30,863 -- INFO -- graph_times     Plotting all projects inside of Projects
Qt: Session management error: None of the authentication protocols specified are supported

--- End standard output ---
--- Graphsample log ---
2016-03-23 16:31:49,572 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/7806rzqSDrunsample/780.bam.qualdepth.png
2016-03-23 16:36:57,424 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/947PQ58Shrunsample/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947PQ58Shrunsample/947.bam.qualdepth.png
2016-03-23 16:37:18,365 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png
2016-03-23 16:37:24,990 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

--- End Graphsample log ---
Projects/947/947.std.log
Projects/947/947.bam.vcf
Projects/947/947.ref.fasta.pac
Projects/947/947.bam.qualdepth.png
Projects/947/947.ref.fasta.ann
Projects/947/flagstats.txt
Projects/947/947.log
Projects/947/947.ref.fasta
Projects/947/947.ref.fasta.bwt
Projects/947/947.ref.fasta.sa
Projects/947/947.bam.qualdepth.json
Projects/947/947.bam
Projects/947/947.bam.bai
Projects/947/947.ref.fasta.amb
Projects/947/947.reads.png
Projects/947/947.bam.consensus.fasta
Projects/947/bwa.log
Projects/947/trim_stats/filtered.947_S32_L001_R1_001_2013_12_17.fastq.trim_stats
Projects/947/trim_stats/filtered.947__1__TI86__2012_08_06__Unk.fastq.trim_stats
Projects/947/trim_stats/filtered.947_R4111_2014_01_29_Den4_Den4_1280_A02.fastq.trim_stats
Projects/947/trim_stats/filtered.947_F2824_2014_01_29_Den4_Den4_1280_G01.fastq.trim_stats
Projects/947/trim_stats/filtered.947_R3415_2014_01_29_Den4_Den4_1280_H01.fastq.trim_stats
Projects/947/trim_stats/filtered.947__2__TI86__2012_08_06__Unk.fastq.trim_stats
Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png
Projects/947/filtered/filtered.947_S32_L001_R1_001_2013_12_17.fastq
Projects/947/filtered/filtered.947_R4111_2014_01_29_Den4_Den4_1280_A02.fastq
Projects/947/filtered/filtered.947_R3415_2014_01_29_Den4_Den4_1280_H01.fastq
Projects/947/filtered/filtered.947__2__TI86__2012_08_06__Unk.fastq
Projects/947/filtered/filtered.947__1__TI86__2012_08_06__Unk.fastq
Projects/947/filtered/filtered.947_F2824_2014_01_29_Den4_Den4_1280_G01.fastq
Projects/947/filtered/filtered.947_S32_L001_R2_001_2013_12_17.fastq
Projects/947/filtered/ngs_filter_stats.txt
Projects/947/trimmed_reads/unpaired_trimmed.fastq
Projects/947/trimmed_reads/filtered.947_S32_L001_R1_001_2013_12_17.fastq
Projects/947/trimmed_reads/filtered.947_R4111_2014_01_29_Den4_Den4_1280_A02.fastq
Projects/947/trimmed_reads/filtered.947_R3415_2014_01_29_Den4_Den4_1280_H01.fastq
Projects/947/trimmed_reads/filtered.947__2__TI86__2012_08_06__Unk.fastq
Projects/947/trimmed_reads/filtered.947__1__TI86__2012_08_06__Unk.fastq
Projects/947/trimmed_reads/filtered.947_F2824_2014_01_29_Den4_Den4_1280_G01.fastq
Projects/947/trimmed_reads/filtered.947_S32_L001_R2_001_2013_12_17.fastq
--- Standard output ---
Using 24 cpus
2016-03-23 16:31:11,420 -- INFO -- runsample       --- Starting 947 --- 
2016-03-23 16:31:11,420 -- INFO -- runsample       --- Starting 780 --- 
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__2__TI86__2012_08_06__Unk.fastq
5004 reads converted
Converting /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.sff to fastq into /opt/ngs_mapper/ngs_mapper/tests/fixtures/functional/947/947__1__TI86__2012_08_06__Unk.fastq
/opt/ngs_mapper/miniconda/lib/python2.7/site-packages/Bio/SeqIO/SffIO.py:991: BiopythonParserWarning: Your SFF file is technically invalid as it is missing a terminal 4 byte null padding region.
  BiopythonParserWarning)
4821 reads converted

2016-03-23 16:31:53,707 -- INFO -- runsample       --- Finished 780 ---

2016-03-23 16:37:16,392 -- INFO -- runsample       --- Finished 947 ---
Using 24 cpus
Qt: Session management error: None of the authentication protocols specified are supported
Qt: Session management error: None of the authentication protocols specified are supported
2016-03-23 16:37:18,365 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png

real	0m2.107s
user	0m2.045s
sys	0m0.110s
2016-03-23 16:37:24,990 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

real	0m9.281s
user	0m13.305s
sys	0m0.169s
Qt: Session management error: None of the authentication protocols specified are supported
Qt: Session management error: None of the authentication protocols specified are supported
Reflen: 1732
Curregion: [1713, 1732, 'LowCoverage']
Reflen: 2193
Curregion: [1371, 2193, 'Normal']
Reflen: 1000
Curregion: [1, 1000, 'Normal']
Reflen: 1538
Curregion: [1517, 1524, 'LowCoverage']
Creating new gap region to cover end of reference: [1524, 1538, 'Gap']
Reflen: 2311
Curregion: [1801, 2311, 'Normal']
Reflen: 1438
Curregion: [1335, 1438, 'LowCoverage']
Reflen: 10650
Curregion: [1, 10650, 'Normal']
Reflen: 861
Curregion: [1, 861, 'Normal']
Reflen: 2318
Curregion: [1617, 2318, 'Normal']
convert: DelegateLibrarySupportNotBuiltIn `QualDepth.pdf' (JPEG) @ error/pdf.c/WritePDFImage/1470.
2016-03-23 16:37:30,863 -- WARNING -- graph_times     Projects/780 ran in only 42 seconds
2016-03-23 16:37:30,863 -- INFO -- graph_times     Plotting all projects inside of Projects
Qt: Session management error: None of the authentication protocols specified are supported

--- End standard output ---
--- Graphsample log ---
2016-03-23 16:31:49,572 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/7806rzqSDrunsample/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/7806rzqSDrunsample/780.bam.qualdepth.png
2016-03-23 16:36:57,424 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/947PQ58Shrunsample/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947PQ58Shrunsample/947.bam.qualdepth.png
2016-03-23 16:37:18,365 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/947/qualdepth/947.bam.qualdepth.Den4_AY618992_1_Thailand_2001_Den4_1.png Projects/947/947.bam.qualdepth.png
2016-03-23 16:37:24,990 -- INFO -- graphsample     Running montage -geometry +1+1 -quality 25 -compress JPEG Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png Projects/780/780.bam.qualdepth.png

--- End Graphsample log ---
Projects/780/780.ref.fasta.ann
Projects/780/780.bam.qualdepth.json
Projects/780/780.ref.fasta.amb
Projects/780/780.log
Projects/780/780.ref.fasta
Projects/780/780.bam.vcf
Projects/780/flagstats.txt
Projects/780/780.std.log
Projects/780/780.bam
Projects/780/780.bam.bai
Projects/780/780.bam.qualdepth.png
Projects/780/780.bam.consensus.fasta
Projects/780/780.ref.fasta.sa
Projects/780/780.ref.fasta.pac
Projects/780/bwa.log
Projects/780/780.reads.png
Projects/780/780.ref.fasta.bwt
Projects/780/trim_stats/filtered.780_S12_L001_R1_001_2014_04_16.fastq.trim_stats
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074922_Managua_2010_PB2_1.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074921_Managua_2010_PB1_2.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074920_Managua_2010_PA_3.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074918_Managua_2010_NP_5.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074915_Managua_2010_HA_4.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074917_Managua_2010_NA_6.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074916_Managua_2010_MP_7.png
Projects/780/qualdepth/780.bam.qualdepth.H3N2_CY074919_Managua_2010_NS_8.png
Projects/780/filtered/filtered.780_S12_L001_R2_001_2014_04_16.fastq
Projects/780/filtered/filtered.780_S12_L001_R1_001_2014_04_16.fastq
Projects/780/filtered/ngs_filter_stats.txt
Projects/780/trimmed_reads/filtered.780_S12_L001_R2_001_2014_04_16.fastq
Projects/780/trimmed_reads/filtered.780_S12_L001_R1_001_2014_04_16.fastq
Pipeline did not produce project file Projects/780/trimmed_reads/780_S12_L001_R2_001_2014_04_16.fastq
Pipeline did not produce project file Projects/780/trimmed_reads/780_S12_L001_R1_001_2014_04_16.fastq
Pipeline did not produce project file Projects/780/trim_stats/780_S12_L001_R1_001_2014_04_16.fastq.trim_stats

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 5 tests in 380.385s

FAILED (failures=1)
```

**Comment by necrolyte2** [comment]
I guess that error happens because I was inside of a `su -` session so Qt could not connect to X session

http://stackoverflow.com/questions/29998451/qt-session-management-error-with-matplotlib-pyplot-plot
